export const FETCH_APARTMENTS_LIST = "FETCH_APARTMENTS_LIST";
export const FETCH_APARTMENT = "FETCH_APARTMENT";
export const FETCH_APARTMENT_ERROR = "FETCH_APARTMENT_ERROR";
export const FETCH_APARTMENTS_LIST_ERROR = "FETCH_APARTMENTS_LIST_ERROR";
export const FETCH_LOCATIONS_LIST = "FETCH_LOCATIONS_LIST";
export const FETCH_LOCATIONS_LIST_ERROR = "FETCH_LOCATIONS_LIST_ERROR";
export const FETCH_APARTMENTS_LOCATION_LIST = "FETCH_APARTMENTS_LOCATION_LIST";
export const FETCH_APARTMENTS_LOCATION_LIST_ERROR = "FETCH_APARTMENTS_LOCATION_LIST_ERROR";
